### ISSUE TITLE
感觉个别地方不太通顺

### ISSUE THREAD

**Issue by freezestudio** [zhongsp/TypeScript#1]
对TypeScript感兴趣了，找到了您的项目。
迫不急待地读了起来，感到您翻译地很好。
但我初学这个语言，感觉您在表述的个别地方不是很好理解，提一点点小小的意见。
再次感谢您的所做的翻译工作。

1、基础类型

在这里：任意值
但是Object类型的变量只是允许你给它赋任意值 -- 但是你不**像**在它上面调用任意方法，

2、变更声明

在这里：作用域规则
其中之一就是，多次声明一个变量**被不会**报错：

还有在这里：重定义及屏蔽
并不是说块级作用域变量不能在函数作用域内声明。 而是块级作用域变量需要在**不用**的块里声明。

还有在这里：块级作用域变量的获取
当我们最初谈起获取用var声明的变量时，我们主要是说**获取后变量**的行为是什么。

**Comment by zhongsp** [comment]
@freezestudio Thanks! 
I've updated the wording base on your comments.
If you'd like to join in this project, please feel free to create PRs! :beers:

**Comment by freezestudio** [comment]
感谢您的工作！
我看得比较慢 : )
