### ISSUE TITLE
GitBook 上错误的语言设置

### ISSUE THREAD

**Issue by tiansh** [zhongsp/TypeScript#108]
打开 https://zhongsp.gitbooks.io/typescript-handbook/content/index.html
html标签上写着 `lang="zh-tw"` ，但是显然文章是简体字写的，导致文章的所有字体都不正确。
看了看也不知道是哪里的问题……
总之可不可以处理一下这个问题，谢谢。

**Comment by zhongsp** [comment]
@tiansh 十分感谢，我研究一下

**Comment by zhongsp** [comment]
@tiansh 修改好了！再次感谢
