### ISSUE TITLE
Review & Sync "Module Resolution.md"

### ISSUE THREAD

**Issue by zhongsp** [zhongsp/TypeScript#124]
https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Module%20Resolution.md

**Comment by freezestudio** [comment]
我是 freezestudio ，这段时间没在使用ts，但是始终在关注您的进度。
道一声“谢谢您”，实在是佩服您的坚持了。

2016-09-20 13:25 GMT+08:00 Patrick Zhong <notifications@github.com>:

**Comment by zhongsp** [comment]
@freezestudio 哈哈，谢谢支持！正是有大家在关注才能坚持更新 :smile:
