### ISSUE TITLE
ASP.NET 5 is dead - Introducing ASP.NET Core 1.0 and .NET Core 1.0

### ISSUE THREAD

**Issue by Craft24** [zhongsp/TypeScript#125]
当我按照这个教程学习TypeScript的时候，  
>5.选择 ASP.NET 5 Empty 工程模板  

到选择工程模板这块时问题来了  
我已经安装过VS2015Update3了补丁也更新过了，死活是找不到aspnet5工程模板，  
去网上搜索很多是让安装  
>Microsoft ASP.NET and Web Tools 2015  

搜这个东西下载下来的是  
>DotNetCore.1.0.1-VS2015Tools.Preview2.0.2.exe  

安装这个东西是各种失败啊，各种搜索无果后，想起来在学习PHP的时候搭建PHP环境时  
需要安装vcredist_x64.exe（C++运行库），装了之后还是提示孩子啊找不到，装了个32位的  
可以了，就想着是不是DotNetCore.1.0.1仅仅装了64位的不行啊，就下载32位的装了，可以了  
上面Tools可以安装了，我疯了。  
一切就绪准备继续TypeScript学习，依然找asp.net 5工程模板无果，怎么办？快哭了  
结果就在google搜索asp.net 5，收到了SCOTT HANSELMAN这货的asp.net 5 is dead，骂了  
半天微软，终于明白asp.net 5工程模板是找不到了，asp.net core webapplication的模板可以  
继续用，最后看到熟悉的project.json我的内心是崩溃的，洪荒之力已经用完了，终于可以开始
学习TypeScript的了。  
我太过纠结了，提个issue的目的是更新下知识库，技术迭代导致这手册难读也算是issue了，keep moving！

**Comment by zhongsp** [comment]
:+1:

**Comment by NewBLife** [comment]
@Craft24 你是要找这个吗？我的有哦！[asp.net 5 模板](https://github.com/NewBLife/train/blob/master/Asp.net%205%20Template.PNG)

**Comment by zhongsp** [comment]
@Craft24 @NewBLife I'm going to close this issue! Thanks for ur comments!
