### ISSUE TITLE
能不能导出个PDF给下载，让人没有网的时候也能看看

### ISSUE THREAD

**Issue by OUZICHENG** [zhongsp/TypeScript#141]
感谢卓越的翻译工作。
现在家里宽带改造，很长一段时间上不了网，手机信号也不好，移动网络不稳定。如果有PDF版可以下载，就不用网也能看了。你觉得呢？

**Comment by Treri** [comment]
可以把整个项目clone下来, 然后找个支持markdown预览的编辑器即可

**Comment by mishengqiang** [comment]
@OUZICHENG 好的，我来负责生成pdf版。

**Comment by mishengqiang** [comment]
* [TypeScript 2.0 中文版 PDF格式](http://www.tslang.cn/typescript2.0中文版.pdf)方便PC查看
* [TypeScript 2.0 中文版 MOBI格式](http://www.tslang.cn/typescript2.0中文版.mobi)方便kindle查看
* [TypeScript 2.0 中文版 EPUB格式](http://www.tslang.cn/typescript2.0中文版.epub)方便移动端查看
* 你可以访问[TypeScript中文网](http://www.tslang.cn/docs/tutorial.html)

**Comment by OUZICHENG** [comment]
@mishengqiang 灰常感谢
