### ISSUE TITLE
求助：关于如何在github创立和管理一个外语文档的翻译项目

### ISSUE THREAD

**Issue by OUZICHENG** [zhongsp/TypeScript#145]
感谢所有贡献者的辛勤工作，提供了这么好的中文文档。
另外，我非常好奇如何管理这样一个共同翻译的项目。我只知道大致的github和gitbook用法。以下是我对于管理这样一个项目的想法和疑问，请给指点，谢谢。
如果是我来做，我可能会这么做：

1. 如果原项目的文档本身就在github上，我想我会先fork一份咯。（但是这里面对另外一种情况我不知道怎么办好，就是原文档没有在github上，或者说没有以git资源形式给出，如android官方的开发指南就没有托管在github，而是以网页的形式直接在他们的网站上发布。写爬虫抓取人家的网页回来改？）
2、github上的文档应该都是MD写的，如果有原文件应该只要分配好每个人翻译的章节，然后各自翻译好之后PR回翻译项目应该就差不多了。

下面基本是疑问：

1.  如何跟进原文档的更新。最理想的情况是我们从原项目fork出项目原文件，翻译完成。但是之后原文档会更新，我们怎么跟进。我的意思如何能锁定原项目文档部分的更新，而其他如程序原代码的更改自动忽略。当官方文档有更新时我们及时修改自己的翻译。甚至于可以提示读者哪里更新了，让之前看过文档的人着重了解新东西。还有一种最坏的情况，就是原文档是网页我们如何跟进这种更新，人肉？
2、MD格式的文档翻译好之后，在github上确认通过，如何及时更新到gitbook，或是我自己为读者设立的网站，让他们能看到最新的内容。有什么工具可以用还是有什么套路可寻。谢谢

麻烦解答尽可能接地气咯，不要说自己搜索一下就会了，搜索了很久还是找不到路，所以才请诸大神赐教。
你可以这样：
解决你的问题可以这样：1、XXXXXXXX2、XXXXXXXX3、XXXXXXXX……
或者
想觉得这些知识推荐你看看这些文章：URL1,URL2,URL3……
或者
有下面这些好用的工具可以用：工具1，工具2，工具3

指条明路我会自己往前走的，先谢过

**Comment by zhongsp** [comment]
1. 如果原文档是像TypeScript-Handbook一样托管在Github上的话比较方便。
只要Watch了仓库，当它有更新的时候就会通知你，而且能看到更新了什么地方。
![image](https://cloud.githubusercontent.com/assets/1198615/20381428/5db50eda-ace2-11e6-96c9-1d2d915c2cf8.png)
要是不是通过Github管理的就不清楚了。
2. 用你的Github帐号登录Gitbook并授权后，当你更新Github上的代码时Gitbook会自动build. <https://developer.gitbook.com/>

**Comment by OUZICHENG** [comment]
@zhongsp 谢谢回复.
对于第一点,如果是原项目只有纯文档还好说,但是如果原项目包含了文档和代码就麻烦了.比如说我知道像React Native 这样的项目,文档和原代码一起托管的,watch之后每天收到非常多的提示,但是里面很多是代码的修改,甚至别人提交的PR, issue都会收到信息,真正文档个性的内容就淹没了.我的意思是如果能只接收文档那个目录的更新信息就好了.
第二点,谢谢,原来是自动的.
其实呢有一个想法,想做个APP,让大家可以在手机上用自己零碎的时间翻译文档.比如从公交的时候.不成熟,想想清楚再与大家分享.

**Comment by OUZICHENG** [comment]
我家又可以上网了,呵呵 @zhongsp
