### ISSUE TITLE
变量声明中的展开操作符在官方文档中找不到对应章节

### ISSUE THREAD

**Issue by Maroon1** [zhongsp/TypeScript#148]
```
let defaults = { food: "spicy", price: "$$", ambiance: "noisy" }; 
let search = { ...defaults, food: "rich" };
```
 其中的对象展开的代码测试运行通不过

**Comment by zhongsp** [comment]
https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Variable%20Declarations.md#spread

**Comment by Maroon1** [comment]
原来typescrip已经更新到2.1.4的版本了，今天更新了一下，编译没问题了，太赞了！
