### ISSUE TITLE
Sync "Advanced Types.md"

### ISSUE THREAD

**Issue by zhongsp** [zhongsp/TypeScript#156]

**Comment by xcatliu** [comment]
type assertion
type predicate

这两个都翻译成类型断言可能会引起误解

**Comment by zhongsp** [comment]
@xcatliu 感谢 我稍后review一下

**Comment by mishengqiang** [comment]
@zhongsp type predicate是类型谓词，type assertion是类型断言。

**Comment by xcatliu** [comment]
贴一段上下文：

> To get the same code working, we’ll need to use a type assertion:
>
> ```ts
> let pet = getSmallPet();
>
> if ((<Fish>pet).swim) {
>     (<Fish>pet).swim();
> }
> else {
>     (<Bird>pet).fly();
> }
> ```

> To define a type guard, we simply need to define a function whose return type is a type predicate:
>
> ```ts
> function isFish(pet: Fish | Bird): pet is Fish {
>     return (<Fish>pet).swim !== undefined;
> }
> ```
>
> `pet is Fish` is our type predicate in this example.
