### ISSUE TITLE
2.6 TypeScript 1.5 章有翻译笔误

### ISSUE THREAD

**Issue by sxp** [zhongsp/TypeScript#157]
比如说, 下面的例子声明了变量 x, y 和 z, 并且分别将它们的值初始化为 getSomeObject().x, getSomeObject().x 和 getSomeObject().x:

应为：

比如说, 下面的例子声明了变量 x, y 和 z, 并且分别将它们的值初始化为 getSomeObject().x, getSomeObject().**`y`** 和 getSomeObject().**`z`**:

**Comment by zhongsp** [comment]
修复了。谢谢。
