### ISSUE TITLE
Add translation for "What's new in TypeScript"

### ISSUE THREAD

**Issue by zhongsp** [zhongsp/TypeScript#18]
Source: https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript

**Comment by vilic** [comment]
这部分正好我有翻译 https://github.com/vilic/typescript-guide/blob/master/wiki/whats-new-in-typescript.md

**Comment by zhongsp** [comment]
@vilic So COOL!

**Comment by vilic** [comment]
:tada:
