### ISSUE TITLE
Tuple 是否可以翻译为多元数组？

### ISSUE THREAD

**Issue by dear-lizhihua** [zhongsp/TypeScript#184]
多元数组看起来更直观，体现为：一是一个数组，二是里面的元素可以是多种类型（即多元）。

**Comment by xcatliu** [comment]
“元组”是一个已经广泛使用的概念了，其他语言中，Tuple 中文都是元组：
https://msdn.microsoft.com/zh-cn/library/system.tuple(v=vs.110).aspx

**Comment by dear-lizhihua** [comment]
好的，以其他语言现有翻译为准吧。
