### ISSUE TITLE
本仓库和站点www.tslang.cn什么关系？

### ISSUE THREAD

**Issue by Sunzhuokai** [zhongsp/TypeScript#186]
rt

**Comment by zhongsp** [comment]
@Sunzhuokai 没有关系。

**Comment by Sunzhuokai** [comment]
![image](https://user-images.githubusercontent.com/8599906/29393826-dd570422-8338-11e7-8290-e3280516f597.png)
@zhongsp

**Comment by mishengqiang** [comment]
@Sunzhuokai www.tslang.cn是我上线的网站，我参与了其中一小部分翻译。www.tslang.cn使用本仓库的翻译文档是经@zhongsp 授权的，详情请看 #51 和 #98 。关于文档里面存在www.tslang.cn的链接，这个是我不小心造成的，我会进行更正。对于造成的错误，我诚挚的道歉：对不起了，以后认真审核后再提交。
