### ISSUE TITLE
诚邀您入驻豆腐丁网站翻译 TypeScript 手册

### ISSUE THREAD

**Issue by xiaohulu** [zhongsp/TypeScript#188]
@zhongsp 您好，您做的 TypeScript 手册翻译工作，对我学习 TypeScript 有很大的帮助，
我写了一个豆腐丁网站，提供友好的翻译功能。
欢迎您了解并提意见。

这是我做的部分翻译，您也可以创建自己的翻译项目。
https://doufuding.com/projects/2

本想给您写邮件，但是找遍网站，并没有发现您留下的邮箱。
如果给您带来不便，敬请谅解。

**Comment by zhongsp** [comment]
@xiaohulu 谢谢邀请，但我近期有其它事情要处理。
