### ISSUE TITLE
Typo in code

### ISSUE THREAD

**Issue by DarkKowalski** [zhongsp/TypeScript#240]
Thers is a [Typo](https://github.com/zhongsp/TypeScript/blame/master/doc/handbook/Classes.md#L385).
According to [official handbook](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Classes.md#abstract-classes), "earch" should be "earth".

**Comment by zhongsp** [comment]
Fixed. Thanks! @DarkKowalski
