### ISSUE TITLE
Translation Suggestions

### ISSUE THREAD

**Issue by MonkSoul** [zhongsp/TypeScript#241]
In the **Variable Declaration** section,

I think the sentence 

> Many JavaScript developers are intimately familiar with this behavior, but if you’re surprised, you’re certainly not alone. 

 should be translated as 

> 很多JavaScript程序员对这种行为已经很熟悉了，但如果很不解，你就不是其中之一。

 better than the 

> 很多JavaScript程序员对这种行为已经很熟悉了，~~但如果你很不解，你并不是一个人。~~

**Comment by rainydew** [comment]
但如果你觉得吃惊，也不必奇怪
