### ISSUE TITLE
Synchronized updates to version 3.5.

### ISSUE THREAD

**Issue by MonkSoul** [zhongsp/TypeScript#247]
At present, the official English documents have been updated to 3.5, and the Chinese translation has lagged behind several versions. What is the current plan?

**Comment by zhongsp** [comment]
Yes.. A few versions of release notes are not translated. I’m trying to keep updating the main content of handbook first. After that will look into release notes and breaking changes, etc.

If you’re interested in translating the documents,  please submit PRs directly. Thanks!
