### ISSUE TITLE
很多链接经常打不开

### ISSUE THREAD

**Issue by JingLMalan** [zhongsp/TypeScript#248]
<img width="690" alt="WX20190809-105228@2x" src="https://user-images.githubusercontent.com/28568280/62750800-fb43e380-ba93-11e9-908c-781efba5dea5.png">

**Comment by zhongsp** [comment]
老铁，能发我一个link吗？我这看的话没这么严重。

**Comment by zhongsp** [comment]
请尝试新的站点：
https://app.gitbook.com/@zhongsp/s/typescript-handbook/
