### ISSUE TITLE
How typescript import a normal js?

### ISSUE THREAD

**Issue by Coralma** [zhongsp/TypeScript#25]
Hi zhongsp,
Thanks for your document. It's really helpful for me to learn the ts. But something I didn't get from you document about how to import a online js into ts.

I want to use baidu map into my typescript. But the baidu map api is totally online. The URL is http://api.map.baidu.com/api?v=2.0&ak=test.

I can't download the baidu map api js into my project. And I can't find a way to import this Online js into my ts. Please give me some suggestion. Thanks so much.

**Comment by zhongsp** [comment]
@Coralma I think what you need is a `bmap.d.ts` file. Please read the section [书写.d.ts文件
](https://github.com/zhongsp/TypeScript/blob/master/doc/handbook/Writing%20Definition%20Files.md).

In the project, use the syntax
```ts
/// <reference path="bmap.d.ts" />
```

In index.html, include `http://api.map.baidu.com/api?v=2.0&ak=test`
Then you could use baidu map api.

**Comment by Coralma** [comment]
Thanks for your reply. But when I develop the bmap.d.ts copying the google.map.d.ts I find some issue. The base variable BMap of baidu map can't be invoked into d.ts file. It always compile error in my Webstorm IDE. Did I miss something?

**Comment by zhongsp** [comment]
Not sure. Can you show your code and errors?

**Comment by Coralma** [comment]
![issue](https://cloud.githubusercontent.com/assets/842458/12601980/a1414852-c4e0-11e5-8e5d-73538d6bae87.png)

It's my webstorm screenshot. The BMap object is baidu map base object. I think I should extend it for my BaiduMap object in my baidu.map.d.ts file. But I don't know where to import the BMap?

I refered the google map sample. Here is the URL: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/googlemaps/google.maps.d.ts

**Comment by zhongsp** [comment]
I think it's what you need to write..

**Comment by Coralma** [comment]
I've solved this issue by webPack external including. But I will keep learning TS. Thanks for your reply.
