### ISSUE TITLE
请求每个页面的document底部增加一点bottom边距

### ISSUE THREAD

**Issue by OfficialYoungX** [zhongsp/TypeScript#258]
每次滑动到页面底部，我都以为还没加载完。
很小的改动，极大的用户体验提升。

**Comment by zhongsp** [comment]
是GitBook上的页面吗？ http://zhongsp.gitbooks.io/typescript-handbook/content/ ？

**Comment by OfficialYoungX** [comment]
> 是GitBook上的页面吗？ http://zhongsp.gitbooks.io/typescript-handbook/content/ ？

这个：https://typescript.bootcss.com
不知道是不是你们的。。。

**Comment by zhongsp** [comment]
哦，这个网站我修改不了，不是我管理的。
