### ISSUE TITLE
请问gitbook跟仓库是同步更新的吗

### ISSUE THREAD

**Issue by Iixianjie** [zhongsp/TypeScript#260]
看gitbook上新增功能那一栏最高到3.1，而仓库里的readme已经3.6了

**Comment by zhongsp** [comment]
@Iixianjie 感谢反馈！刚刚升级了一下GitBook，新的地址：https://app.gitbook.com/@zhongsp/s/typescript-handbook/

理想情况下GitHub和GitBook是同步的。GitHub有提交的话，GitBook会自动更新。但如果有Build Error的话，可能就会卡住。
