### ISSUE TITLE
手册 - 接口 - 额外属性检查 的任意数量其他属性代码实例

### ISSUE THREAD

**Issue by YongzeYao** [zhongsp/TypeScript#266]
gitbook上没有更新到最新的代码。是什么原因？

**Comment by zhongsp** [comment]
GitBook的地址更新了：https://app.gitbook.com/@zhongsp/s/typescript-handbook/handbook/interfaces

**Comment by dongtc** [comment]
新地址会跳转到https://zhongsp.gitbook.io/typescript-handbook/

```ts
interface SquareConfig {
  color?: string;
  width?: number;
  [propName: string]: any;
}
```
这段还是没更新上去呢
