### ISSUE TITLE
在线阅读地址挂了，我用爬虫爬了数据，新建了一个在线文档是否考虑添加到readme.md上

### ISSUE THREAD

**Issue by bosens-China** [zhongsp/TypeScript#270]
https://bosens-china.github.io/Typescript-manual/dist/
这个是我创建的文档地址，用的是vuePress

原来的文档不知道是不是网络波动的原因，一直打不开

**Comment by zhongsp** [comment]
:+1: 可能是GitBook被Qiang了吧，我是能访问的 :D
