### ISSUE TITLE
gitbook上的代码示例显示有误

### ISSUE THREAD

**Issue by zhunrong** [zhongsp/TypeScript#287]
目前发现在定义这类接口的示例代码中，显示有问题。
如图：
![image](https://user-images.githubusercontent.com/25678595/78557187-e5fd9f80-7842-11ea-9ec6-93dd7acf90c1.png)
![image](https://user-images.githubusercontent.com/25678595/78557312-22c99680-7843-11ea-857d-cf6f91879b96.png)

**Comment by zhunrong** [comment]
目前发现有好几处类似的，这是其中一处：
[接口-可索引的类型](https://zhongsp.gitbook.io/typescript-handbook/handbook/interfaces#ke-suo-yin-de-lei-xing)

**Comment by iSozL** [comment]
+1

**Comment by zhongsp** [comment]
@zhunrong 感谢反馈。这段时间我发现GitBook网站打不开了。。可能得考虑换个工具了

**Comment by NekoSola** [comment]
> @zhunrong 感谢反馈。这段时间我发现GitBook网站打不开了。。可能得考虑换个工具了

啊，我说今天想看看大佬翻译的文档，gitbook显示404
然后pull了大佬的项目，本地用Typora看感觉还行，还能同步拉取大佬最新的翻译内容。
赞美大佬！

**Comment by mywaiting** [comment]
这个网址可以打开 https://zhongsp.gitbooks.io/typescript-handbook/content/ 还是挂在 gitbook 下面的，不过就是不是最新版本吧

**Comment by zhongsp** [comment]
兄弟们，目前不会在GitBook上发布了。这个工具有些奇怪的问题，特别是对内地的用户。目前，还是直接在GitHub上看Markdown吧。
