### ISSUE TITLE
Instead of forking the original typescript repository, you've cloned, repushed the code (edited obviously), and claimed it as your own.

### ISSUE THREAD

**Issue by DGKSK8LIFE** [zhongsp/TypeScript#290]
This is very disrespectful to the initial developers of Typescript and is considered bad practice on github.

**Comment by DGKSK8LIFE** [comment]
Oh. Sorry. I had a misunderstanding as I cannot read the Chinese alphabet. I didn't realize this was documentation. Sorry.

**Comment by zhongsp** [comment]
never mind
