### ISSUE TITLE
官网中文支持

### ISSUE THREAD

**Issue by wszgrcy** [zhongsp/TypeScript#306]
今天发现官方网站已经有切换中文选项,但是发现只有极少部分被汉化,不知道是不是来自大佬手笔
希望能合官方合并,这样以后如果有什么更新,也可以依赖官方的维护,更容易让更多人看到
发现目前已汉化的部分
https://www.typescriptlang.org/zh/tsconfig#Module_Resolution_Options_6174

不知道大佬们能不能和官方联系下,把这块合并进来?

**Comment by zhongsp** [comment]
@wszgrcy 感谢提醒，我有时间去了解一下。

**Comment by zhongsp** [comment]
尝试性地在官方翻译了一个文档：https://www.typescriptlang.org/zh/docs/handbook/nightly-builds.html
整体上感觉网站还处于建设早期，还需要一段时间。

**Comment by zhongsp** [comment]
Answered in https://github.com/zhongsp/TypeScript/issues/325
