### ISSUE TITLE
Website display issue of page [handbook/enums].

### ISSUE THREAD

**Issue by VergeDX** [zhongsp/TypeScript#307]
![image](https://user-images.githubusercontent.com/25173827/100819763-c5482100-3487-11eb-9d74-7b6b9811405a.png)
![image](https://user-images.githubusercontent.com/25173827/100819908-0fc99d80-3488-11eb-835c-858acb15718a.png)
Like the image above, “联合类型” word of [tslang.cn](https://www.tslang.cn/docs/handbook/enums.html#computed-and-constant-members) not display as hyperlink form.
@zhongsp

**Comment by zhongsp** [comment]
@VergeDX I'm not a maintainer of that website.
