### ISSUE TITLE
最新发布了该手册的线上阅读地址：http://zhongsp.github.io/TypeScript

### ISSUE THREAD

**Issue by hotoo** [zhongsp/TypeScript#308]
gitbooks.io 太慢了，为什么不直接生成 epub,pdf 会至少放在 gh-pages 分支。

**Comment by zhongsp** [comment]
现在已经不再往GitBooks上发布了，可以直接浏览相应的Markdown文件。

**Comment by hotoo** [comment]
搜索引擎还是会优先列出 gitbooks.io 上的。

**Comment by zhongsp** [comment]
最新的线上阅读地址为：http://zhongsp.github.io/TypeScript

Light Mode:
![724209834](https://user-images.githubusercontent.com/1198615/158100176-68a36917-05f2-4e31-821e-f7d5f99bbf6b.jpg)

Dark Mode:

![1079537796](https://user-images.githubusercontent.com/1198615/158100184-9e262696-0ecd-4873-bd19-dff1fa7651e8.jpg)

说明：https://github.com/zhongsp/TypeScript#%E4%B8%8A%E6%96%B0  FYI, @hotoo
