### ISSUE TITLE
关于在“高级类型”一章中“分布式有条件类型”这一小节中最后一个例子的问题

### ISSUE THREAD

**Issue by cindiou** [zhongsp/TypeScript#326]
文档中指明不可以嵌套有条件类型；举出了下面这个例子，会出错；但是经检验并不会出错，运行的tsc版本是4.3.5
`type ElementType<T> = T extends any[] ? ElementType<T[number]> : T;`

测验代码如下：
`const arr = [1, 2, [3, 4, [5, "6"], true]];`
`type AllTypeFromArr = ElementType<typeof arr>;`
`const a: AllTypeFromArr = "1";`
`const b:AllTypeFromArr = 158;`
`const c:AllTypeFromArr = false;`

**Comment by zhongsp** [comment]
@cindiou 你好，TypeScript 从 4.1 版本开始放宽了对递归的有条件类型的限制，见版本说明 [递归的有条件类型](https://github.com/zhongsp/TypeScript/blob/dev/zh/release-notes/typescript-4.1.md#%E9%80%92%E5%BD%92%E7%9A%84%E6%9C%89%E6%9D%A1%E4%BB%B6%E7%B1%BB%E5%9E%8B)

我稍后更新一下，谢谢。
