### ISSUE TITLE
文件名称中有空格的无法打开

### ISSUE THREAD

**Issue by notinmood** [zhongsp/TypeScript#330]
凡是文件名称中带有空格的文件，都打不开。这个问题没有人反馈吗，还是大家都可以打开，只有我打不开。
比如：
https://zhongsp.gitbooks.io/typescript-handbook/content/doc/handbook/Utility%20Types.html
https://zhongsp.gitbooks.io/typescript-handbook/content/doc/handbook/Utility Types.html

**Comment by zhongsp** [comment]
GitBook 早已弃用，但是 GitBook 不允许我删除内容 - -
新的在线阅读地址为：http://www.patrickzhong.com/TypeScript/zh/reference/utility-types.html
这个体验更好。
