### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by Chulan-824** [zhongsp/TypeScript#335]
http://www.patrickzhong.com/TypeScript/zh/handbook/unions-and-intersections.html

2.5联合类型第一个例子

为了取代any，我们可以为padding参数使用 元组类型 ❎

为了取代any，我们可以为padding参数使用 联合类型 ✅

**Comment by zhongsp** [comment]
Fixed, online book will be updated later. Thanks @Chulan-824 !
