### ISSUE TITLE
手册（进阶）——3.1 高级类型 代码报错

### ISSUE THREAD

**Issue by gjssss** [zhongsp/TypeScript#339]
[高级类型——交叉类型](http://www.patrickzhong.com/TypeScript/zh/reference/advanced-types.html#%E4%BA%A4%E5%8F%89%E7%B1%BB%E5%9E%8Bintersection-types) 中，代码块报错。
```typescript
function extend<First, Second>(first: First, second: Second): First & Second {
    const result: Partial<First & Second> = {};
    for (const prop in first) {
        if (first.hasOwnProperty(prop)) {
            (result as First)[prop] = first[prop];
        }
    }
    for (const prop in second) {
        if (second.hasOwnProperty(prop)) {
            (result as Second)[prop] = second[prop];
        }
    }
    return result as First & Second;
}

class Person {
    constructor(public name: string) { }
}

interface Loggable {
    log(name: string): void;
}

class ConsoleLogger implements Loggable {
    log(name) {
        console.log(`Hello, I'm ${name}.`);
    }
}

const jim = extend(new Person('Jim'), ConsoleLogger.prototype);
jim.log(jim.name);
```
[Playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAUwB5WWAJgHgGIwBOAzlADSIDKyECWAfABTBGkBciBJ5ixNdHarWwBKDl1KIAZFX7ZEAbwCwAKETrEwyYWTEQAGygcACgENCsU-vyso02cIaIAvIoC+AblUbEwOIURGLTsAB0I4EMQYJBZuEUVvHw0YYEDY0gA6AAtTYgB5AHcwY3CQ5AsAT0YwiJF45TUkpsYdPUNEXM5bEQBtGpCAXRdfWz7Sga9GprdE9Rmp339A4MR+qKQ+R3rZpJTAzbps3MLi0vKoKv66hIWm9RbdAztOoTpe-qHXA+wxiImdnzzQE7HRQECEJCtJ4dYhdbj2V7YSbzVQQfS5WHGcrEBA3HzBQggaD+aogABG+hgEEQYFMAFtkBxSIRogBzeqIeYolTRDCEYCmCDIRAAGTgrNZpgpwoaPn04sYtIZTKgLLA7I4ADc4DAsMjVKj0cRYQBhBA4-TIMUS8pROkhS0MsBQWHWyXSvEaeWsxX05DbW4aLRwS0Zb2MAAGAAlkPp5RQAJIAcjpiAAJAolcg3BkIyJJsCVNyVgArGCp1xoDDYRXIAqILEkBCMJMAKXLSZEFDNYAtVvFrPKGRqUDgFzK+dUZbpYYV04yWcnKiAA)
其中不是很清晰解释的内容，感觉的意思是将`Person`的`name`属性和`ConsoleLogger`的`log(name)`方法合并成一个对象最后调用。其中
* `hasOwnProperty`处应该为`Object.prototype.hasOwnProperty.call(obj, prop)`
* `log(name)`应显式表明类型`log(name: string)`
* 最后发现无论如何都无法获取到`ConsoleLogger`的`log`方法（使用`for(prop in ConsoleLogger.prototype)`无法获取），无法实现函数返回值`result`具有`log`函数，所以才没有提交PR，请作者大大讲解一下。:(

**Comment by zhongsp** [comment]
Hi @gjssss ,

报错是因为启用了 `strictNullChecks` 编译选项。如果关闭该选项，代码就可以运行了。
![image](https://user-images.githubusercontent.com/1198615/188546727-a2862e5a-8f4b-441c-8408-9bfe6b1bbf31.png)
![image](https://user-images.githubusercontent.com/1198615/188547758-cc17c99b-3605-4cce-87b7-7c3ac6d4cd1d.png)

但根本原因是这段代码确实有 bug，因为它直接在 `first` 上调用了 `first.hasOwnProperty(prop)`，但 `first` 上不一定有该方法。例如 `first = Object.create({}, null)`。

`extend` 函数将两个参数的自身可枚举属性复制到 `result` 上。您说的无法获取 `log` 方法指的是哪里？

**Comment by gjssss** [comment]
> Hi @gjssss ,
> 
> 报错是因为启用了 `strictNullChecks` 编译选项。如果关闭该选项，代码就可以运行了。 ![image](https://user-images.githubusercontent.com/1198615/188546727-a2862e5a-8f4b-441c-8408-9bfe6b1bbf31.png) ![image](https://user-images.githubusercontent.com/1198615/188547758-cc17c99b-3605-4cce-87b7-7c3ac6d4cd1d.png)
> 
> 但根本原因是这段代码确实有 bug，因为它直接在 `first` 上调用了 `first.hasOwnProperty(prop)`，但 `first` 上不一定有该方法。例如 `first = Object.create({}, null)`。
> 
> `extend` 函数将两个参数的自身可枚举属性复制到 `result` 上。您说的无法获取 `log` 方法指的是哪里？

您好，谢谢您的回答，我关闭了`strictNullChecks`的编译选项，我这边说的`log`方法指的是最后一句代码`jim.log(jim.name);`
![image](https://user-images.githubusercontent.com/74909529/188573697-d20f44f3-9536-4065-8cc3-c34423f9172c.png)
而当我试图显示其`log`属性时显示undefined
![image](https://user-images.githubusercontent.com/74909529/188574438-b1f852b2-792a-48fe-bdd4-c5a9fc74da93.png)
为什么会出现这种情况呀，看样子好像是函数`extend`中`second`对象没有`log`属性，我试着打印`second`的内容发现显示出`[LOG]: ConsoleLogger: {} `是一个空对象，不清楚出了什么状况。
下面是我运行的完整代码，不知道是不是因为我代码出了错。
```js
function extend<First, Second>(first: First, second: Second): First & Second {
    const result: Partial<First & Second> = {};
    for (const prop in first) {
        if (first.hasOwnProperty(prop)) {
            (result as First)[prop] = first[prop];
        }
    }
    for (const prop in second) {
        if (second.hasOwnProperty(prop)) {
            (result as Second)[prop] = second[prop];
        }
    }
    // 显示second时是空对象
    console.log(second);
    return result as First & Second;
}

class Person {
    constructor(public name: string) { }
}

interface Loggable {
    log(name: string): void;
}

class ConsoleLogger implements Loggable {
    log(name: string) {
        console.log(`Hello, I'm ${name}.`);
    }
}

const jim = extend(new Person('Jim'), ConsoleLogger.prototype);
// 运行错误
jim.log(jim.name);
// console.log(jim); // jim对象只有name属性
```
最后谢谢您的回答和热心帮助！

**Comment by zhongsp** [comment]
@gjssss Aha! 我在重现的时候顺手设置了 `target: es5` 所以没问题，Playground 默认应该是 `ESNext`。手册里写了，可能没注意：`下面是如何创建混入的一个简单例子("target": "es5")：`。

在目标为 `ES5` 时，TS 会将 `class` 转换成 `function`，而 `ESNext` 则直接使用 `class`。这两者对可枚举属性的定义不同。`ES5` 下 `log` 是可枚举属性，内部属性 `[[Enumerable]]: true`。而 `ES6` 以后，`ConsoleLogger.prototype` 上的 `log` 是不可枚举属性，内部属性 `[[Enumerable]]: false`。

**Comment by gjssss** [comment]
@zhongsp 啊！谢谢！我可能没搞清楚`("target": "es5")`是什么意思，谢谢！麻烦啦！
