### ISSUE TITLE
關於 https://typescript.bootcss.com/ 網站內容錯誤。

### ISSUE THREAD

**Issue by Dalufishe** [zhongsp/TypeScript#343]
不清楚此站和本項目的關係為何，但就我看來為本項目的鏡像版本。其中`內容有許多錯誤` (版本過時等問題, Tuple可否擴充問題)

偏偏在 google 搜尋名列前茅，有極大誤導人的嫌疑 (像我 QQ )

**Comment by zhongsp** [comment]
这个网站不是我维护的。
