### ISSUE TITLE
 Discuss a noun Translation

### ISSUE THREAD

**Issue by freezestudio** [zhongsp/TypeScript#4]
在**类型兼容性**一节，起始部分：
TypeScript里的类型兼容性基于结构子类型的。 结构类型是只一种只使用其成员来描述类型的方式。 它正好与名义类型形成对比。

改为如下是不是会更好一些？：

TypeScript里的类型兼容性 **是** 基于结构子类型的。 结构类型是 ~~**只**~~ 一种只使用其成员来描述类型的方式。 它正好与 **具名** 类型形成对比。

**nominal** 这个词计算机词典中解释为：标称，额定，指定

**Comment by zhongsp** [comment]
前面2处我认同你的改动 :+1: 
最后一处有点疑问，*具名类型*没有表达不太准备，因为结构性子类型（Structural Typing）也是有名子的。现在译文里的*名义类型*其实在我看来也很难表达出内在的区别。但是有参考，其它文档里出现过把`nominal typing`译成`名义类型`，比如：https://msdn.microsoft.com/zh-cn/library/bb399353(v=vs.110).aspx 。你有没有找到相关参考的文档，是将它译为`具名类型`或是其它的，我们再商量一下。
目前可以先应用前两处改动，你愿意提交PR来修改吗，还是我来？

**Comment by freezestudio** [comment]
我的理解：结构性类型表达的意思是只要某些结构其子类型是兼容的，编译器会忽略它们的名字，而将它们视为相同的类型。nominal类型则是一个类型有一个类型的名字，同一个作用域中不能有2个或多个相同的名字，即nominal类型将类型的名字视为类型的一部分。以C++为例，C++是强类型的语言，如果有2个结构：struct a{int n;}; struct b{int n;}; 即使它各方面都相同，或者为都为空，这两个结构是不同的，struct a != struct b; 若要赋值a=b，必须强转，而且多数情况下是危险的行为。c++中称结构a或b有标签名，这些名字是有意义的，也是强类型语言的一个必要措施。
如果与结构性类型相比较的话，译成 **语义性类型** 会不会更好？

**Comment by zhongsp** [comment]
可以，但感觉**语义性类型**与起决定性作用的**类型的名字**好像没有直接关联？或者用**名义性类型**？再或者**名义（语义性）类型**？或者干脆就**语义性类型**。
我觉得用哪个都可以，只要是能理解针对类型的解释就好，翻译有时很难找到完全对应的汉语词。你可以挑选一个你认为最好的理解的来使用，都可以接受 :smile:

**Comment by freezestudio** [comment]
要不，加个注释？必竟我们不是“语言律师”

**Comment by zhongsp** [comment]
Okay :+1:
