### ISSUE TITLE
「极客学院」电子书原创作者邀请

### ISSUE THREAD

**Issue by twq0076262** [zhongsp/TypeScript#40]
您好：我是极客学院 wiki 组的，2月底给您发过邮件，一直没有收到回复。

想和您沟通一下《TypeScript Handbook（中文版）》合作事情。

qq/微信/手机:15010141884

网址：wiki.jikexueyuan.com 可以了解一下

期待您的回复

**Comment by twq0076262** [comment]
「极客学院」电子书原创作者邀请

**Comment by zhongsp** [comment]
@twq0076262 Replied by email
