### ISSUE TITLE
《接口》章节，示例代码里 是不是写错了!

### ISSUE THREAD

**Issue by miaochw** [zhongsp/TypeScript#45]
if (config.color) {
    // Error: Property 'collor' does not exist on type 'SquareConfig'

这个地方 if 里边应该是  config.collor   吧， 因为你是想给出一个错误的案例，结果 写的是正确的代码。

**Comment by zhongsp** [comment]
@miaochw 你说的是，这里想给出一个错误的案例，只是这个错误发生在下面的一个语句里`newSquare.color = config.collor`

```ts
  if (config.color) {
    // Error: Property 'collor' does not exist on type 'SquareConfig'
    newSquare.color = config.collor;  // Type-checker can catch the mistyped name here
  }
```

:smile:
