### ISSUE TITLE
请问TypeScript中文手册是否可以授权给TypeScript中文网使用

### ISSUE THREAD

**Issue by mishengqiang** [zhongsp/TypeScript#51]
你好，两个月前给你的Gmail邮箱发送过邮件，向你询问是否可以将你翻译的TypeScript中文手册授权TypeScript中文网使用事情，但你一直没有回复，在此向你询问是否可以将你翻译的TypeScript中文手册授权TypeScript中文网使用？
我的联系方式：邮箱mishengqiang@outlook.com

**Comment by zhongsp** [comment]
@mishengqiang I agree.
