### ISSUE TITLE
howto:in d.ts declare same instance method and same instance variable has same name

### ISSUE THREAD

**Issue by freezestudio** [zhongsp/TypeScript#73]
e.g.

JS Class : Test
Instance Method : var number =test.size();
Instance Variable : size    Type:Number

or
see: http://www.nodegit.org/api/diff_file/

thanks!

**Comment by zhongsp** [comment]
Property and method with the same name is not make sense. I think API documentation is strange. You could check `notegit` source code and make sure `diffFile.size` and `diffFile.size()` both is available.

**Comment by freezestudio** [comment]
Thank you, I take a closer look.
