### ISSUE TITLE
Add translation for "Add a quick-start guide on ASP.NET Core"

### ISSUE THREAD

**Issue by freezestudio** [zhongsp/TypeScript#80]
source: https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/quick-start/asp-net-core.md

**Comment by freezestudio** [comment]
Translation file:
[asp_net_core.zip](https://github.com/zhongsp/TypeScript/files/212275/asp_net_core.zip)

**Comment by zhongsp** [comment]
@freezestudio :heart: I'll merge it. Thanks!
