### ISSUE TITLE
你授权的TypeScript中文网文档部分今天上线

### ISSUE THREAD

**Issue by mishengqiang** [zhongsp/TypeScript#98]
你好，
之前你曾经授权给[TypeScript中文网](http://www.tslang.cn/)中文文档今天上线了。你是否要确认一下。

**Comment by zhongsp** [comment]
@mishengqiang Outstanding work! Thanks!

**Comment by mishengqiang** [comment]
@zhongsp 是否考虑生成pdf格式的电子书？

**Comment by zhongsp** [comment]
没有，更新比较频繁

**Comment by mishengqiang** [comment]
@zhongsp 那要不要做一版pdf  然后定期更新pdf  现在有一些开发者想要pdf 方便离线查询文档。Gitbook生成pdf应该不是问题。

**Comment by zhongsp** [comment]
@mishengqiang Okay, 没问题

**Comment by mishengqiang** [comment]
@zhongsp 好，那我来生成pdf，完事儿先给你发一份确认，确认通过后我再分发给开发者。

**Comment by zhongsp** [comment]
Closed.
